app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/site.scss
app/Views/ScBooking/AvailableTimes.cshtml
app/Views/ScBooking/CaseBooked.cshtml
app/Views/ScBooking/CaseConfirm.cshtml
app/Views/ScBooking/ConferenceType.cshtml
app/Views/ScBooking/Index.cshtml

All pages:
- Changed spacing for the page header.
- Added the arrow icon to the back navigation link.
- Changed button size on mobile.
Home page:
- Added small labels for the input fields (class, number).
- Changed the position of the question circle icon.
- Changed spacing for the light gray background.
- Removed the horizontal line under the page header.
- Added hover colour to the table (each of the search results).
Conference type page (step 2):
- Changed spacing for the light gray background.
- Added the external link icon to the text link.
Available times page (step 3), Case confirm page (step 4):
- Changed some spacing.
Case booked page:
- Added the external link icon to the text link.

SCJ-13: Updated styling to page headers

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/_variables.scss
app/ClientSrc/sass/site.scss
app/Views/ScBooking/ConferenceType.cshtml
app/Views/ScBooking/Index.cshtml

Updated selected states styling for buttons (hover/focus), time picker, and, case picker based on [the bc gov design system](https://developer.gov.bc.ca/Design-System/Colour-Palette).
Fixed the [SCJ-25](https://oxd.atlassian.net/jira/software/projects/SCJ/boards/7?selectedIssue=SCJ-25) bug.
***The colours of the buttons might be changed after the internal review with the team.**

SCJ-15: Updated selected states styling

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/site.scss

Changed the secondary button colour to grey to make difference from the primary button.
Fixed SCJ-26, 31.

SCJ-26-31: Fixed bug and changed the secondary button colour

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/site.scss
app/Views/ScBooking/CaseConfirm.cshtml
app/Views/ScBooking/Index.cshtml

Fixed SCJ-37, 42. 
Changed some spacing.

SCJ-37-42: Fixed bug

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/_variables.scss
app/Views/ScBooking/AvailableTimes.cshtml

Applied calendar visual design for date picker.
@CelloLiu I added the new button for the calendar, but I just added `id="datepicker"` for the button in `AvailableTimes.cshtml`. Please feel free to add functions/code for the new button.

SCJ-33: Applied visual design for date picker

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/site.scss
app/ClientSrc/vue/booking-casesearch/availabletimes.vue

Made the previous header design back as adding another black colour.
Small fix for the typography, and case time picker.

SCJ-00: Small fix

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/site.scss
app/ClientSrc/vue/booking-casesearch/availabletimes.vue
app/Views/ScBooking/AvailableTimes.cshtml
app/Views/ScBooking/CaseConfirm.cshtml
app/Views/ScBooking/Index.cshtml

Fixed SCJ-55, 58, and 60.
Changed some spacing and layout.

SCJ-55-58-60: Fixed bug

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/site.scss
app/Views/ScBooking/Index.cshtml

Applied new style for no search results for a case number.
Small fix for the button and link spacing on mobile.

SCJ-59-67: Applied new style for no results and small fix

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/site.scss
app/Views/CoaBooking/CaseBooked.cshtml
app/Views/CoaBooking/CaseConfirm.cshtml
app/Views/CoaBooking/CaseSearch.cshtml

@molund As we discussed, the COA doesn't keep 100% of old styling. Header, footer, background colour, font, and primary/secondary buttons are changed as same as the SC. However, the layout is pretty the same as the previous version. Let me know if you have any questions.

SCJ-61: Maintained COA styling

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/site.scss

SCJ-56: Design QA fixes

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/sass/site.scss
app/Views/ScBooking/CaseSearch.cshtml
app/Views/ScBooking/Index.cshtml

Fixed colour contrast issue for the error messages
Added aria-label for the select form

SCJ-27: Fixed colour contrast issue

---

app/ClientSrc/sass/site.scss
app/Controllers/CoaBookingController.cs
app/Services/CoaBookingService.cs
app/Services/CoaCacheService.cs
app/Startup.cs
app/Utils/CoaSessionBookingInfo.cs
app/ViewModels/CoaCaseConfirmViewModel.cs
app/ViewModels/CoaCaseSearchViewModel.cs
app/Views/CoaBooking/CaseConfirm.cshtml
app/Views/CoaBooking/CaseSearch.cshtml
app/wwwroot/js/coa.js

CoA initial start

---

app/Views/Home/Index.cshtml

A minor update to some text on the homepage view, to match what's in the latest wireframe

SCJ-117: Update homepage copy

---

app/ClientSrc/sass/coa.scss
app/Views/CoaBooking/CaseSearch.cshtml
app/wwwroot/js/coa.js

Added back a question that was accidentally deleted when SCJ-108 was implemented
When "Appeal" is selected:
- The hearing type dropdown should appear for criminal cases (e.g. 42024) <-- **this question was deleted**
- The "factum" question should appear for civil cases (e.g. 39000)

SCJ-108: Add back deleted question

---

app/Services/CoaBookingService.cs
app/Services/MailService.cs
app/ViewModels/EmailViewModel.cs
app/Views/CoaBooking/CaseConfirm.cshtml
app/Views/CoaBooking/EmailText.cshtml

Email updates for appeal hearings

SCJ-122: Emails

---

app/Services/CoaBookingService.cs
app/Views/CoaBooking/CaseBooked.cshtml
webservices/FakeOnlineBookingClient.cs

- Implemented booking for chambers hearings
- Updated the fake client to only return future available dates

SCJ-125: Implement chambers booking submission

---

app/Views/CoaBooking/EmailText.cshtml

Hide the type of appeal from the emails for chambers hearings

SCJ-133: Hide Type Of Appeal Hearing for chambers

---

app/Views/CoaBooking/EmailText.cshtml

Added alternate email text for appeal hearings

SCJ-135: Different email text for chambers and appeal

---

app/ClientSrc/sass/coa.scss

Design requested a quick change to update the padding in the date boxes

SCJ-121: Update date box padding

---

app/Views/CoaBooking/CaseConfirm.cshtml
app/Views/CoaBooking/CaseSearch.cshtml
app/Views/Home/Index.cshtml

Some minor updates to the text in the CoA page templates. Copied and pasted from the client's word doc, except one line where I added a comma 🙏  as I [noted in Jira](https://oxd.atlassian.net/browse/SCJ-161?focusedCommentId=18706)

SCJ-161: Update text in CoA template

---

app/Controllers/ApiController.cs
app/Controllers/CoaBookingController.cs
app/Controllers/HomeController.cs
app/Controllers/ScBookingController.cs
app/Properties/launchSettings.json
app/SCJ.Booking.MVC.csproj
app/Startup.cs
app/Utils/OpenIdConnectHelper.cs
app/Views/Home/NotAuthorized.cshtml
app/appsettings.json

SCJ-168: Added keycloak and authorization

---

app/Controllers/HomeController.cs
app/Startup.cs
app/Views/CoaBooking/_Layout.cshtml
app/Views/ScBooking/_Layout.cshtml
app/Views/Shared/_Layout.cshtml
app/appsettings.Production.json
app/appsettings.Test.json
app/appsettings.json

SCJ-169: Update the logout to use Keycloak

---

app/ClientSrc/vue/TrialTimeSelect/RegularBooking.vue
app/ClientSrc/vue/TrialTimeSelect/Tabs.vue
app/Controllers/ScBookingController.cs
app/Services/ScBookingService.cs
app/Utils/ScSessionBookingInfo.cs
app/ViewModels/ScCaseConfirmViewModel.cs
app/ViewModels/ScCaseSearchViewModel.cs
app/Views/ScBooking/BookingType.cshtml
app/Views/ScBooking/CaseConfirm.cshtml
app/Views/ScBooking/Index.cshtml
app/Views/ScBooking/Partial/AvailableTimes/_Conference.cshtml
app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_Conference.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_ContactForm.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_FairUseBooking.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_RegularBooking.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_Trial.cshtml
app/Views/ScBooking/TrialBooked.cshtml

Pushing to divide up the remaining work on Step 4a

SCJ-145: Step 4a in progress

---

app/Services/SelectListService.cs
app/Utils/ScCourtClass.cs
app/ViewModels/ScCaseSearchViewModel.cs
app/Views/ScBooking/Index.cshtml

NOBUG: Decouple Court Classes from the model

---

app/Services/ScBookingService.cs
app/Services/ScCacheService.cs

Added trial booking formulas to the cache and hooked it up to GetAvailableTrialDatesAsync

SCJ-145: Added Trial Booking Formulas to cache

---

app/Services/ScBookingService.cs

Fixed court class on confirmation screen.  
Eventually this whole thing need to be refactored so we aren't using ScCaseSearchViewModel on subsequent steps.

NOBUG: Fix for blank court class on confirmation screen

---

app/Controllers/ScBookingController.cs
app/Services/ScBookingService.cs
app/Utils/ScFormulaType.cs
app/Utils/ScSessionBookingInfo.cs
app/ViewModels/ScCaseConfirmViewModel.cs
app/ViewModels/ScCaseSearchViewModel.cs
app/Views/ScBooking/Partial/AvailableTimes/_Conference.cshtml
app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_Conference.cshtml

- Hooked up the API calls to get available dates for trials
- Renamed BookingRegistryId to HearingBookingRegistryId because it looks like this field is only for hearings

SCJ-144: Hooked up API calls for available dates

---

app/ClientSrc/vue/TrialTimeSelect/RegularBooking.vue
app/ClientSrc/vue/TrialTimeSelect/Tabs.vue
app/Controllers/ScBookingController.cs
app/Services/ScBookingService.cs
app/Utils/ScSessionBookingInfo.cs
app/ViewModels/ScBookingTypeViewModel.cs
app/ViewModels/ScCaseConfirmViewModel.cs
app/ViewModels/ScCaseSearchViewModel.cs
app/Views/ScBooking/BookingType.cshtml
app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_Trial.cshtml

Started the process of having separate view models for each step.
I won't split up any other steps until @duncan-oxd is finished making changes to the other screens.

SCJ-144: Refactor BookingType to use it's own model

---

app/ClientSrc/vue/TrialTimeSelect/RegularBooking.vue
app/ClientSrc/vue/TrialTimeSelect/Tabs.vue
app/Controllers/CoaBookingController.cs
app/Controllers/ScBookingController.cs
app/Services/CoaBookingService.cs
app/Services/ScBookingService.cs
app/Startup.cs
app/Utils/OpenIdConnectHelper.cs
app/Utils/ScSessionBookingInfo.cs
app/ViewModels/ScCaseConfirmViewModel.cs
app/ViewModels/ScCaseSearchViewModel.cs
app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_Trial.cshtml
database/ApplicationDbContext.cs
database/Migrations/20240314160547_Keycloak.Designer.cs
database/Migrations/20240314160547_Keycloak.cs
database/Migrations/20240314203106_LastLogin.Designer.cs
database/Migrations/20240314203106_LastLogin.cs
database/Models/BookingHistory.cs
database/Models/OidcUser.cs

- Split BookingHistory into 2 tables and added more tracking fields
- Added a User table
- Use Keycloak claims and ASP.NET claims instead of siteminder headers

SCJ-176: Updated the database to work with Keycloak

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/vue/TrialTimeSelect/FairUseBooking.vue
app/ClientSrc/vue/TrialTimeSelect/RegularBooking.vue
app/ClientSrc/vue/TrialTimeSelect/Tabs.vue
app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml

Updates to the styles and templates for Step 3 - mostly the error/warning alert elements.

SCJ-173: Update Step 3 templates and styles

---

app/Services/ScBookingService.cs
app/Views/ScBooking/Email-Trial-Regular.cshtml

Added confirmation email for Regular trial bookings

SCJ-149: Add regular booking email

---

app/ClientSrc/vue/TrialTimeSelect/FairUseBooking.vue
app/ClientSrc/vue/TrialTimeSelect/Tabs.vue
app/Controllers/ScBookingController.cs
app/Services/ScBookingService.cs
app/ViewModels/ScCaseSearchViewModel.cs
app/ViewModels/TrialEmailViewModel.cs
app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml

Hooked up template variables to _some_ values from the API, but need to confirm if they're correct.
The template and model changes should be good either way, but may need to tweak the values being set in the controller...

SCJ-180: Populate trial template placeholders

---

app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml

A small fix, I missed one of the template placeholders last time - probably because it breaks onto two lines and I was searching the project with regex 😓

SCJ-180: populate template placeholder

---

webservices/Fixtures/CoAAvailableDatesFixture.cs
webservices/Fixtures/CoAChambersApplicationsFixture.cs
webservices/Fixtures/CoAClassInfoFixture.cs
webservices/Fixtures/ScAvailableBookingTypesFixture.cs
webservices/Fixtures/ScAvailableDatesByLocationFixture.cs
webservices/Fixtures/ScAvailableTrialDatesFixture.cs
webservices/Fixtures/ScBookingHearingResultFixture.cs
webservices/Fixtures/ScFormulaLocationsFixture.cs
webservices/Fixtures/ScLocationFixture.cs

Updated the fixture data
- Added more trial dates
- Fixed compiler warnings & suggestions
- Moved static dates further into the future

SCJ-191: Fixture data updates

---

app/Controllers/ScBookingController.cs
app/Services/ScBookingService.cs
app/Utils/ScHearingType.cs
app/ViewModels/ScCaseSearchViewModel.cs
app/Views/ScBooking/Index.cshtml
test/RemoteApiTests.cs
webservices/Fixtures/ScFormulaLocationsFixture.cs

More refactoring & code cleanup

SCJ-192: Cleanup

---

app/Services/ScBookingService.cs

Sort trial date options chronologically after they are returned from the API

SCJ-195: Sort trial date options chronologically

---

app/ClientSrc/sass/_bootstrapOverrides.scss
app/ClientSrc/vue/TrialTimeSelect/FairUseBooking.vue
app/ClientSrc/vue/TrialTimeSelect/RegularBooking.vue
app/ClientSrc/vue/TrialTimeSelect/Tabs.vue

Some miscellaneous fixes from the design QA feedback. James provided CSS for most of the changes, but I used slightly different styles to achieve the same result in a few cases (text-align: center instead of using flexbox, etc) but it's mostly copied and pasted from the ticket

SCJ-193: Update Step 3 styles from design QA

---

app/Controllers/ScBookingController.cs
app/Services/CoaBookingService.cs
app/Services/DbWriterService.cs
app/Services/ScBookingService.cs
app/Services/ScCacheService.cs
app/Utils/ScSessionBookingInfo.cs
app/ViewModels/ScAvailableTimesViewModel.cs
app/ViewModels/ScCaseSearchViewModel.cs
app/ViewModels/ScConferenceEmailViewModel.cs
app/ViewModels/ScTrialEmailViewModel.cs
app/Views/ScBooking/AvailableTimes.cshtml
app/Views/ScBooking/BookingType.cshtml
app/Views/ScBooking/ConferenceBooked.cshtml
app/Views/ScBooking/Email-CPC.cshtml
app/Views/ScBooking/Email-CV-AWS.cshtml
app/Views/ScBooking/Email-CV-PTC.cshtml
app/Views/ScBooking/Email-CV-TCH.cshtml
app/Views/ScBooking/Email-JCC.cshtml
app/Views/ScBooking/Email-JMC.cshtml
app/Views/ScBooking/Email-TMC.cshtml
app/Views/ScBooking/Email-Trial-FairUse.cshtml
app/Views/ScBooking/Email-Trial-Regular.cshtml
app/Views/ScBooking/Index.cshtml
app/Views/ScBooking/Partial/AvailableTimes/_Conference.cshtml
app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_Conference.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_ContactForm.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_Trial.cshtml
app/Views/ScBooking/TrialBooked.cshtml

Mostly renaming, but also removed some attributes and changed the behaviour of a few others.

NOBUG: Refactored ScSessionBookingInfo

---

SCJ.Booking.sln
app/SCJ.Booking.MVC.csproj
app/Services/COA/CoaBookingService.cs
app/Services/COA/CoaCacheService.cs
app/Services/DataWriterService.cs
app/Services/SC/ScConferenceBookingService.cs
app/Services/SC/ScCoreService.cs
app/Services/SC/ScTrialBookingService.cs
app/Utils/OpenIdConnectHelper.cs
database/ApplicationDbContext.cs
database/Migrations/20240423213446_EmailQueue.Designer.cs
database/Migrations/20240423213446_EmailQueue.cs
database/Models/QueuedEmail.cs
database/SCJ.Booking.Data.csproj
database/ServiceCollectionExtensions.cs
database/ServiceConfig.cs
database/Utils/LogHelper.cs
service/Program.cs
service/SCJ.Booking.TaskManager.csproj
service/Services/MailQueueService.cs
service/Services/MailService.cs
service/appsettings.json

Mail queue implementation part 1

SCJ-155: Refactor emails to use a queue

---

app/Services/SC/ScCoreService.cs
app/Utils/ScSessionBookingInfo.cs

Reverted part of the previous commit because the search form was losing a value

SCJ-200: Reverted part of the last commit

---

app/Controllers/ScBookingController.cs
app/Services/COA/CoaBookingService.cs
app/Services/COA/CoaCacheService.cs
app/Services/SC/ScCacheService.cs
app/Services/SC/ScConferenceBookingService.cs
app/Services/SC/ScCoreService.cs
app/Services/SC/ScTrialBookingService.cs
app/Services/SelectListService.cs
app/Utils/OpenIdConnectHelper.cs
app/ViewModels/SC/ScCaseSearchViewModel.cs
app/Views/_ViewImports.cshtml
database/Constants/CoaCaseType.cs
database/Constants/CoaHearingType.cs
database/Constants/ScCourtClass.cs
database/Constants/ScFormulaType.cs
database/Constants/ScHearingType.cs
database/Constants/ScPhoneNumbers.cs
service/Program.cs
service/Services/MailQueueService.cs
service/Utils/LogHelper.cs
service/servicesettings.json
webservices/FakeOnlineBookingClient.cs
webservices/Fixtures/ScFormulaLocationsFixture.cs

Stripped from refactoring out from the main PR to make the commit smaller

CM-152: Refactoring to prep for lottery runner

---

app/ClientSrc/vue/TrialTimeSelect/FairUseBooking.vue
app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml

Some small-ish changes to the template on trial booking "Step 3" detailed in this ticket: https://oxd.atlassian.net/browse/SCJ-184
One of the files hadn't had the auto-formatting applied so a lot of whitespace changed 😬 - Be sure to "hide whitespace changes" in the diff view or it will be tough!
I guess all cshtml files are supposed to have 4-space indents!

SCJ-184: Update template wording on step 3

---

app/Views/ScBooking/Index.cshtml

The last branch for quick text edits today 😌 
Updated some descriptive text and a field label on the first step of the SC booking

SCJ-223: Update text on step 1 page

---

app/Views/Home/Index.cshtml

A quick update to the text on the homepage, no code changes

SCJ-220: Update homepage copy

---

app/Services/CoaBookingService.cs
app/Services/ScBookingService.cs
app/Startup.cs
app/Utils/OpenIdConnectHelper.cs
database/Models/OidcUser.cs

Added code to integrate with BC Wallet. 
If you run this version on your local machine, the SSO page won't apear.  Use #193 if you want to run it locally.

SCJ-205: Integrate with BC Wallet (master branch)

---

app/Services/COA/CoaBookingService.cs
app/Services/SC/ScConferenceBookingService.cs
app/Services/SC/ScTrialBookingService.cs
app/Startup.cs
app/Utils/OpenIdConnectHelper.cs
app/appsettings.Development.json
app/appsettings.Production.json
app/appsettings.Test.json
app/appsettings.json
database/Models/OidcUser.cs

I created two PRs for this since the master branch and develop branch are very diverged right now
You will also need to update the value of KEYCLOAK_CLIENT_SECRET in your .env file if you want to run this locally.

SCJ-205: Integrate with BC Wallet (develop branch)

---

app/Views/ScBooking/BookingType.cshtml

A small change to make the word "or" bold in an alert message.
I had to wrap the whole thing in a `span` to keep it working with the flex layout

SCJ-228: Update alert message HTML

---

app/ViewModels/SC/ScBookingTypeViewModel.cs
app/ViewModels/SC/ScCaseSearchViewModel.cs

Small updates to the names of a couple of the validation fields.

SCJ-217: Update field names

---

app/Controllers/HomeController.cs
app/Startup.cs
app/Views/Home/Index.cshtml
app/Views/Home/Sso.cshtml

Implemented a placeholder custom SSO page
This is intended to demo better, and also give us more time to work the kinks out of the sign-in flow while we wait for final design and copy.

SCJ-230: Added custom SSO page

---

database/Migrations/20240627204844_CascadeDeletes.Designer.cs
database/Migrations/20240627204844_CascadeDeletes.cs
database/Models/ScTrialDateSelection.cs
taskrunner/Services/LotteryCleanupService.cs

Take advantage of cascading deletes instead of deleting relations manually

SCJ-154: Cascade deletes to ScTrailDateSelections

---

app/Views/ScBooking/AvailableTimes.cshtml
app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_ContactForm.cshtml

Verbiage tweaks to change "Choose" to "Request", plus a fix for some missing whitespace in some updated link text (I didn't notice it before 🤔)

SCJ-235: Update "Request" wording & whitespace

---

app/Views/ScBooking/Partial/CaseConfirm/_ContactForm.cshtml
app/Views/ScBooking/Partial/CaseConfirm/_FairUseBooking.cshtml

More minor template changes, with some conditional text on the final submit button

SCJ-239: Update "Review Your Request" view text

---

app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml

Updating some text formatting that I missed/wasn't mentioned in the Jira ticket 😅 
1. Prevent the line from breaking inside the date strings, and prefer the " to " between them
2. Make the booking period dates bold

SCJ-236: Update text formatting in "How This Process Works"

---

app/Views/Home/Index.cshtml

Updating the button text to be more generic, now that there's a second option besides BCeIDs
(The buttons take you to the `/sso` page if you're not logged in)

SCJ-248: Change login button text

---

app/Controllers/ScBookingController.cs

Updates to an error message to match what's in the wireframes

SCJ-246: Update error message text

---

app/Views/ScBooking/BookingType.cshtml

Update to the wording on one of the form questions

SCJ-234: Update question wording

---

app/ClientSrc/sass/global.scss
app/Views/CoaBooking/CaseBooked.cshtml
app/Views/CoaBooking/_Layout.cshtml
app/Views/ScBooking/CaseBooked.cshtml
app/Views/ScBooking/_Layout.cshtml

Updated instances of "login/logout" to have a space in the template. I only udpated the templates here, and not any routes or variable names.
I also updated the stylesheet for the SSO page to use an existing variable instead of hardcoding the mobile breakpoint.
This one's merging into `master` as a hotfix to be patched back into `develop` as we discussed on slack 👍

SCJ-260: Update auth/SSO wording in templates

---

app/Views/Home/Sso.cshtml

Capitalizing a W that was lowercase in the designs 😅 
This one's merging into `master` - #223 also changes the link text a bit, so there might be a conflict to merge them together. I can rebase something or cherry pick if that makes it easier. If not, just remember this branch is only changing one letter 😄

SCJ-231: Update link text

---

app/ClientSrc/vue/LongChambersTimeSelect/LongChambersTimeSelect.vue
app/Services/SC/ScCacheService.cs
app/Services/SelectListService.cs
tests/RemoteApiTests.cs
webservices/FakeOnlineBookingClient.cs
webservices/Fixtures/ScLongChambersHearingSubTypes.cs

- Hooked up scCHHearingSubTypeAsync()
- Implemented fake method and created fixture data for scCHHearingSubTypeAsync()
- Updated more chambers wordiing in the step 3 vue app.
- Changed the implementation of RemoteApiTests to use the .env file

SCJ-300: API integration
