- app/ClientSrc/sass/_bootstrapOverrides.scss
- app/ClientSrc/sass/_variables.scss
- app/ClientSrc/sass/global.scss
- app/Views/CoaBooking/CaseSearch.cshtml
Mostly minor tweaks to the wording and font sizes/spacing on the search page.
The bigger thing from the Figma mockup that I did here was adding "invalid" styles to the radio button controls. These might soon be redundant if we hide the "Next" button, but I added a function in the template to add a class name if there are validation errors for a given field. Let me know if I did that right, or please advise a better way to do it 😅 
Also, it looks like my editor wants to trim trailing white space from lines I haven't touched. A couple of them accidentally got included in the diff here. If it makes PR diffs too weird, I could do a quick branch to just trim it from all files once and for all. We can chat about it if you have a preference!
> SCJ-119: Update search page content

- app/ClientSrc/sass/coa.scss
- app/ClientSrc/sass/global.scss
- app/Views/CoaBooking/CaseConfirm.cshtml
- app/Views/CoaBooking/CaseSearch.cshtml
- app/wwwroot/js/coa.js
Updates to the "Next" and "Restart Search" button styles: color, positioning, include a ⬅️ icon in the Restart button:
The two buttons are initially hidden until you enter something in the Court File Number text box:
Notes:
- the buttons won't hide again if you go and delete your input, but that's an easy change if we want to do that
- I also updated the "Send request" and "cancel" buttons for consistent styling on the confirmation page:
-
> SCJ-124: Update Restart/Next buttons

- app/ViewModels/CoaCaseSearchViewModel.cs
- app/Views/CoaBooking/CaseSearch.cshtml
It looks like most of the changes mentioned in the wireframe PDF have already been implemented here too, so it was just one change to the wording for the hearing length. I updated the getter in the model because it's only used in that one spot (as far as I can tell?) Let me know if that's incorrect!
> SCJ-121: Update results page content

- app/Views/CoaBooking/CaseSearch.cshtml
- app/wwwroot/js/coa.js
The interaction of this form was changed in SCJ-112, but the button should not be clickable until after a date is selected.  Clicking the button before selecting a date was causing the form to go into a bad state.
> SCJ-112: Hide the "Confirm selection" button until a date is chosen

- app/Controllers/CoaBookingController.cs
- app/Services/CoaBookingService.cs
- app/ViewModels/CoaCaseSearchViewModel.cs
- app/Views/CoaBooking/CaseConfirm.cshtml
- app/Views/CoaBooking/CaseSearch.cshtml
I'm not sure when the `is` keyword was added to C# for nullable booleans, but it seems to work way better than what we were doing previously. 
- Made all nullable boolean default to false when referenced in code
- Use the `is` keyworkd for conditional checks instead of null coalescing. 
This might possibly break a few things, but I think it makes debugging easier in the long run.
> NOBUG: Made nullable booleans more readable

- app/Views/CoaBooking/CaseSearch.cshtml
- app/wwwroot/js/coa.js
A bunch of small-ish changes to the file number checkboxes:
1. Checkboxes (and radio buttons) don't support the `readonly` property (Didn't know that until today) - the app already has hidden inputs to make sure the values are included in the request payload, and the unchangeable checkboxes become `disabled` in later steps, so I've made the searched value `disabled` on the form.
I experimented with ignoring checkbox interaction with javascript, but I think it's more obvious if the box is disabled. Let me know if I should change that.
2. Updated some logic that was selecting checkboxes incorrectly
3. I also nested the checkboxes inside the `label` tags, so you can click anywhere on the label to toggle the checkbox.
4. Removed the red text "Only one related file number..." notice, which was …
> SCJ-128: Update file number checkbox handling

- app/Views/CoaBooking/CaseConfirm.cshtml
- app/wwwroot/js/coa.js
I tested and fixed a few scenarios where the user could use the keyboard to submit an invalid form, and then get into a state where they can't move forward. 
It was more likely to happen by accidentally hitting space/enter/arrow keys than some malicious person trying to fill the db with bogus bookings, but still good to prevent it.
I added an `allowSubmit` boolean that prevents form submissions until it's set `true` by the validation logic.
Also made a few selectors and checks more specific to make it all work as expected.
> NOBUG: Prevent invalid keyboard submits

- openshift/helm/scjob/values-prod.yaml
- openshift/helm/scjob/values-test.yaml
This is a hotfix for production. However, the Helm chart upgrade has already been, run so this PR just adds the change to source control.
The environment variable ASPNETCORE_ENVIRONMENT is supposed to be set according to the environment, and it causes the application to load the correct environment override file for `appsettings.json`.  i.e.. `appsettings.Test.json` and `appsettings.Production.json`
Without having this environment variable correctly set, everything defaults to `Development`
`appsettings.Production.json` is important because it has the prod links for both BCeID registration and Siteminder logout.
> SCJ-136: Add missing helm environment variable override to test and prod

- app/Views/CoaBooking/CaseSearch.cshtml
A quick update to the warning text, which previously was specific to just appeals. Now it's more general so it applies to both kinds of hearings
> SCJ-130: Update coa warning message text

- app/ClientSrc/sass/coa.scss
- app/Views/CoaBooking/CaseSearch.cshtml
Some minor tweaks to the breakpoints and spacing in the COA date selection.
I noticed there's a spot around 450px width where the buttons wrap differently for a bit and then go back to a single column. 
If it's supported in all of our target browsers, I think it wouldn't be much work to change this section from css `flex` to a `grid` and make those breakpoints less fragile (if the padding/margins of other elements change, for example)
> SCJ-121: Update date selection spacing

- test/RemoteApiTests.cs
Fixed a broken test. The failure was caused by old dates in the fixture data.
> NOBUG: Fix broken test

- app/ClientSrc/vue/ApplicationTypeSelect/ApplicationTypeSelect.vue
Design requested a small tweak to the spacing of the options in the Application Type selection modal window
> SCJ-123: Reduce modal option spacing

- app/ClientSrc/sass/global.scss
- app/Views/CoaBooking/CaseSearch.cshtml
- app/wwwroot/js/coa.js
Two small fixes as discussed on Slack today:
1. Tweaked the padding in the homepage footer element so it doesn't scroll a few pixels when the content fits in the viewport
2. Added a `form-scroll-section` class to some elements, and some code to scroll to the last `form-scroll-section` on the page when the page loads. This will scroll new form sections into view as they are "revealed" when you submit sections of the form.
I also added a `scroll-padding-top` CSS rule on small screens so the fixed header bar won't cover up the top part when it auto-scrolls things into view.
> SCJ-138: Fix scroll positions

- app/Views/CoaBooking/CaseBooked.cshtml
- app/Views/ScBooking/BookingType.cshtml
- app/Views/ScBooking/CaseBooked.cshtml
After some discussion with Winnie, some quick tweaks to the "danger" error styles:
There were two existing "danger" styles and I've updated them to be consistent (same font weight, same icon)
On the Trial booking form, I added another "danger" alert with a different icon to indicate that you can't continue in that condition
> SCJ-158: Update error styles

- app/ClientSrc/sass/global.scss
- app/ClientSrc/vue/TrialTimeSelect/FairUseBooking.vue
- app/ClientSrc/vue/TrialTimeSelect/Tabs.vue
- app/package-lock.json
- app/package.json
This branch adds a Vue component package called `vuedraggable` to implement the drag and drop reordering of the chosen dates in the fair use trial booking screen.
It posts the values as "YYYY-MM-DD" strings in an array called `SelectedDates`. I see there are separate tasks in Jira for the backend stuff, so I didn't add the variable to the model or anything in this branch. Let me know if it would make sense to do any of that here.
I also made a bunch of miscellaneous style tweaks based on some feedback from Winnie, and
> SCJ-143: Add drag & drop in fair use date selection

- app/Controllers/HomeController.cs
- app/Controllers/ScBookingController.cs
- app/Services/ScBookingService.cs
- app/Services/ScCacheService.cs
- app/Utils/ScHearingType.cs
- app/Utils/ScSessionBookingInfo.cs
- app/ViewModels/IndexViewModel.cs
- app/ViewModels/ScCaseSearchViewModel.cs
- app/Views/Home/Index.cshtml
- app/Views/ScBooking/BookingType.cshtml
- app/wwwroot/js/sc.js
This implements the new `GetAvailableBookingTypes` API method to get the list on the "Choose your booking type" SC step.
In the end, I tried to make these changes _minimally invasive_ so there are probably a lot of things I can do to clean it up or optimize it; let me know if you have ideas!
> SCJ-140: Use GetAvailableBookingTypes API method

- app/ClientSrc/vue/ApplicationTypeSelect/ApplicationTypeSelect.vue
- app/ViewModels/CoaCaseSearchViewModel.cs
- app/Views/CoaBooking/CaseConfirm.cshtml
- app/Views/CoaBooking/CaseSearch.cshtml
- app/wwwroot/js/coa.js
Mostly changes to the validation logic for the COA booking form:
If you pick "Chambers" and select "No" for the "Dates agreed upon?" question, you are shown a new warning message but you can still continue to the next step. I split apart a validation rule that applied to several radio button groups and gave them each their own validation rules with specific logic.
Everything else should be the same, logic-wise.
The task also included some minor template changes (capitalization + show the same warning on the confirmation page)
> SCJ-160: Allow to chambers to continue without agreed dates

- app/Services/CoaBookingService.cs
- app/ViewModels/EmailViewModel.cs
- app/Views/CoaBooking/CaseSearch.cshtml
- app/Views/CoaBooking/Email-Appeal.cshtml
- app/Views/CoaBooking/Email-Chambers.cshtml
- app/Views/Home/Index.cshtml
A small tweak to include the "Agreed upon" answer in the emails for CoA bookings.
For Appeals, it will always be "Yes" because you can't proceed if you answer "No", but I made it dynamic anyway so it's consistent with the Chambers email template.
Also fixes a typo on the homepage 🤪 
And styles on a warning element
> SCJ-175: Update homepage, add "Agreed" to emails

- app/Services/CoaBookingService.cs
- app/ViewModels/EmailViewModel.cs
- app/Views/CoaBooking/CaseSearch.cshtml
- app/Views/CoaBooking/Email-Appeal.cshtml
- app/Views/CoaBooking/Email-Chambers.cshtml
- app/Views/Home/Index.cshtml
Same changes as #103 but this one merges into `develop`.
Maybe the extra PR isn't necessary, but the resulting HTML on the homepage is different so this might avoid conflicts when we merge.
> SCJ-175: (DEV) Update homepage, add "Agreed" to emails

- app/Views/Shared/_Layout.cshtml
A tiny change to make the "touch" menu appear at the "medium" 768px breakpoint, instead of "large" 991px
> SCJ-172: Adjust menu breakpoint

- app/ClientSrc/vue/TrialTimeSelect/RegularBooking.vue
- app/ClientSrc/vue/TrialTimeSelect/Tabs.vue
- app/Controllers/ScBookingController.cs
- app/Services/ScBookingService.cs
- app/Utils/ScSessionBookingInfo.cs
- app/ViewModels/ScCaseConfirmViewModel.cs
- app/ViewModels/ScCaseSearchViewModel.cs
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
- app/Views/ScBooking/Partial/CaseConfirm/_Trial.cshtml
The latest changes, hopefully not messed up by a bunch of rebases. 
As of yet, there are still some `@TODO` stuff remaining, but the code to call `BookTrialHearingAsync` is in place (for Regular bookings, not Fair-Use yet)
Remaining stuff:
I suppose this will become "Step 4b" for the regular booking types, and then I'll implement the Fair Use ones in a separate branch for Step 4a. That one should be much quicker once all of this groundwork has been laid out!
> SCJ-145: Call API methods for booking "Regular" trial

- app/Controllers/ScBookingController.cs
- app/Services/ScBookingService.cs
- app/Views/ScBooking/Partial/CaseConfirm/_RegularBooking.cshtml
Added some very basic error handling to the "BookTrial" method. If the selected booking date is no longer available by the time you submit the form, it will show a simple error message on the same page instead of continuing to the next view.
I noticed some of the other values on the page become blank when it reloads; I don't know if it's related to this ticket, or part of a larger thing we need to fix/refactor. (Saving and reading values from the booking service instead of the postdata). I think this happens in a few places. Should I create a ticket in Jira to fix it up, or tackle it as part of SCJ-146?
> SCJ-146: Throw error if selected regular date is unavailable

- app/ClientSrc/sass/global.scss
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
A quick fix for the trial date selector Vue component. Before the Vue component mounted, you could sometimes see a quick flash of content, including the red error blocks. 
This branch adds `v-cloak` directives, which get removed when the component mounts, to simply hide the component until it's ready to render.
> SCJ-146: Hide trial date selection until it mounts

- app/ClientSrc/vue/TrialTimeSelect/FairUseBooking.vue
- app/Controllers/ScBookingController.cs
- app/Services/ScBookingService.cs
- app/Utils/ScSessionBookingInfo.cs
- app/ViewModels/ScCaseConfirmViewModel.cs
- app/ViewModels/ScCaseSearchViewModel.cs
- app/Views/ScBooking/CaseConfirm.cshtml
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
- app/Views/ScBooking/Partial/CaseConfirm/_Conference.cshtml
- app/Views/ScBooking/Partial/CaseConfirm/_ContactForm.cshtml
- app/Views/ScBooking/Partial/CaseConfirm/_FairUseBooking.cshtml
- app/Views/ScBooking/Partial/CaseConfirm/_Trial.cshtml
Hooked up the "CaseConfirm" page for "Fair use" trial booking types. I also had to move some paragraphs between template files because the Fair Use page has different text than the others.
Most of the changes made for the regular trial bookings also affected this one, so this branch is smaller. The same bugs are present where the app crashes if you go back from step 4 to step 2, but Step 3 still still work, at least! And your previously-selected dates will be selected in the date picker.
I created SCJ-178 in the backlog to fix the problems of values becoming null if you navigate back and forth.
I also regret trying to re-use the existing "date" variable for the Regular booking; maybe we'll change that some time soon to clean things up... but at least Fair Use has all of its own variable …
> SCJ-145: Implement fair use confirmation page

- app/Services/ScBookingService.cs
- app/ViewModels/TrialEmailViewModel.cs
- app/Views/ScBooking/Email-Trial-FairUse.cshtml
- app/Views/ScBooking/Email-Trial-Regular.cshtml
Renamed the existing `GetEmailBody` method and created a new one for Trial bookings.
Regular booking email will be in SCJ-149, following this
> SCJ-148: Add lottery email confirmation

- app/Startup.cs
- app/Utils/OpenIdConnectHelper.cs
Removed the custom code (copied from WorkBC) that handles OIDC refresh tokens.  It seems like the default settings for the standard bcgov keycloak gold domain are long enough that we won't need to worry about refreshing, and this code was failing because we are not storing the access_token or the refresh_token.  
This can be reverted if it causes issues, but then we'll need to store the additional tokens and ask the mid-tier group to increase the maximum header size.
> NOBUG: Remove code for oidc refresh

- app/Services/ScBookingService.cs
- app/Views/ScBooking/Email-Trial-FairUse.cshtml
- app/Views/ScBooking/Email-Trial-Regular.cshtml
- app/Views/ScBooking/Index.cshtml
- app/Views/ScBooking/TrialBooked.cshtml
We were supposed to have the "location prefix" in the file number, like `KE G10107` but it was only showing in some of the form steps. I was manually adding `locationPrefix` to the templates in later steps, but today I noticed that there was a getter that was already supposed to add that value to the fileNumber (it just wasn't working because the value was blank in the session).
I added a hidden field to the index template so `LocationPrefix` will get set correctly in the session, and removed the places I had manually added it it to the template.
> SCJ-185: Fix location prefix in file number

- database/ApplicationDbContext.cs
- database/Migrations/20240402184218_FairUseBookingRequests.Designer.cs
- database/Migrations/20240402184218_FairUseBookingRequests.cs
- database/Models/ScTrialBookingRequest.cs
- database/Models/ScTrialDateSelection.cs
- test/RemoteApiTests.cs
Added two new tables for storing booking requests.
These tables were designed fulfill the following requirements:
1. Must contain the information needed to send final emails 
- _i.e. "you got your booking" or "you didn't get your booking"_
2. Must contain info needed to call `BookTrialHearingAsync`
3. Must contain info needed to call `AvailableTrialDatesByLocationAsync`
4. Must contain info needed to control the cron jobs & trigger bookings
** More fields will be added later for point number 4 above, and also to handle data retention & purging requirements
> SCJ-127: Create database schema for fair-use bookings

- app/Controllers/ScBookingController.cs
- app/Services/ScBookingService.cs
- app/Utils/ScSessionBookingInfo.cs
- app/ViewModels/ScAvailableTimesViewModel.cs
- app/ViewModels/ScCaseConfirmViewModel.cs
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
- app/Views/ScBooking/Partial/CaseConfirm/_RegularBooking.cshtml
- app/Views/ScBooking/TrialBooked.cshtml
This changes the `SelectedRegularTrialDate` logic to always use its own DateTime variable, instead of piggy-backing on the existing "Date/FullDate/HearingDate"/etc. variables that exist for the conference booking. It seemed like a good idea at the time to use the existing patterns, but after doing the fair use booking I realized it would make more sense to have a dedicated variable for this too.
Hopefully it also clears up some of the conversion between DateTime and String. Let me know if anything else can be improved!
> SCJ-188: Use a specific DateTime var for trial booking date

- app/ClientSrc/sass/_bootstrapOverrides.scss
- app/ClientSrc/vue/HearingTimeSelect/HearingTimeSelect.vue
Some minor tweaks to the "tertiary" button class - I believe this is only used on that one swiper-column date picker component.
Previously: the button color would change when the button was _focused_, and wouldn't necessarily reflect the selection state.
Now: Selection state changes on mousedown instead of a full click, so you're less likely to hit a button without changing the selection. Now "selected" buttons will be highlighted, even if you focus a different button by pressing tab, for example.
It's not perfect, but it should cut down on most of the cases that cause confusion
> SCJ-208: Fix hearing date selection highlights

- app/Views/ScBooking/RequestSubmitted.cshtml
A small fix for [SCJ-209](https://oxd.atlassian.net/browse/SCJ-209) that changes the displayed end date/time on the "Your Request is Submitted" page to the `FairUseBookingPeriodEndDate` instead of the `EndDate`.
`FairUseBookingPeriodEndDate` is also nullable so I added the same `?? "[N/A]"` from the line below, but I also want to confirm that. Let me know if anything needs to change!
> SCJ-209: Use period end date in template

- app/ClientSrc/vue/TrialTimeSelect/Tabs.vue
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
Some updates to the "Fair use disabled" message that displays on the "Choose Trial Date(s)" page:
1. Hid the yellow banner on larger screens, and put the banner contents into the tab itself:
(The yellow banner still shows on smaller screens)
2. Updated the contents of the banner with the new message. I'm using the "period end date" variable to determine the "Current" and "Next" month values.
3. A minor style tweak to force the tabs to be equal width. (A longer message was making the tabs uneven sizes and wrapping weirdly)
This is for [SCJ-180](https://oxd.atlassian.net/browse/SCJ-180) - let me know if there's anything else to change here!
> SCJ-180: Update "fair use disabled" message

- app/Controllers/CoaBookingController.cs
- app/Views/CoaBooking/CaseBooked.cshtml
- app/Views/CoaBooking/CaseConfirm.cshtml
- app/Views/CoaBooking/CaseSearch.cshtml
- app/Views/Home/Index.cshtml
- app/Views/Shared/_Layout.cshtml
This was a backlogged ticket left over from when we were working on the COA - it updates the URL routes to be in kebab case, for consistency with the SC routes.
For `Restart` -> `restart`, I don't think the case makes a difference on a windows server, but .. just to be safe.
If we decide to keep these changes, since the app has been online for a long time, we'll probably also need to add 301 redirects from the old URLs to the new ones 🤔
> SCJ-183: Update COA routes to kebab-case

- app/ClientSrc/sass/_bootstrapOverrides.scss
- app/ViewModels/SC/ScAvailableTimesViewModel.cs
- app/Views/ScBooking/AvailableTimes.cshtml
Fixed two issues on the "Available dates" page from [SCJ-216:](https://oxd.atlassian.net/browse/SCJ-216)
1. The calendar in the date picker uses table cells for the days, but it uses _span tags_ for the months and years 😵 so the styles were breaking there. I changed a CSS selector to prevent that. (Just wrapped it in `.datepicker-days {}`, so hide whitespace in the diff)
2. If there are no dates available for a given location+hearing type, the top date picker would be broken and the bottom one would be empty. I updated the code to prevent "firstOrDefault" from returning the minimum date ("0001-01-01")* But then after discussion with UX, I just made it hide that whole section if the dates list is empty. Try it out and let me know what you think.
* I can revert this change now that it's …
> SCJ-216: Fix date picker issues on "Available dates"

- app/ViewModels/SC/ScBookingTypeViewModel.cs
- app/ViewModels/SC/ScCaseSearchViewModel.cs
- app/Views/ScBooking/Index.cshtml
This adds "Display" data attributions to a couple of fields to make the validation error messages more readable.
I also added a `flex-basis` style to one of the field wrappers so it doesn't expand and break the layout when there's an error message displaying (see screenshots below)
Empty state:
Before:
After fixing the flex basis:
> SCJ-217: Fix Error message text

- app/Views/ScBooking/BookingType.cshtml
Changed the portion of the text that's inside/outside the hyperlink tag to match the wireframes mentioned in [SCJ-218](https://oxd.atlassian.net/browse/SCJ-218)
The other two changes are just auto-formatting... Maybe I should do another pass to try to apply auto formatting in all the CSHTML files so it doesn't muddy up other branches and diffs like this. (edit: I'll put up a PR after today's minor changes are merged)
> SCJ-218: Update Step 2 link text

- app/Views/ScBooking/AvailableTimes.cshtml
A quick fix to the issue I introduced in #185 (mentioned on Slack)
Swapping around the cases in the `if` statement:
1. First check if it's a trial
2. If it's not a trial, then show an error if there are no hearing dates available
3. If there _are_ dates available, show the date pickers as usual
(Steps 1 and 2 were reversed before, so it would prevent you from booking trials if the location had no hearing dates)
> SCJ-216: Fix trial/hearing type check logic

- app/Views/ScBooking/AvailableTimes.cshtml
Fixing a small typo that slipped through when I was updating the message on "Available times"
> SCJ-216: Fix typo in registry message

- app/SCJ.Booking.MVC.csproj
- taskrunner/SCJ.Booking.TaskRunner.csproj
- taskrunner/Services/LotteryCleanupService.cs
- taskrunner/Utils/LogHelper.cs
- taskrunner/servicesettings.json
1. Fixed an issue with the taskrunner where logging levels couldn't be set using appsettings or environment variables.
2. Changes some logging in the LotteryCleanupService to use Debug-level logging instead of Information
> NOBUG: use appsettings to control taskrunner log levels

- app/Startup.cs
- app/appsettings.Production.json
- app/appsettings.Test.json
- app/appsettings.json
Based on email from dt.support@gov.bc.ca:
> I added the configuration to both test and prod so you should be good to go. Please note that the name of the pres_req_conf_id is as follows:
> - verified-person-bcpc-test for test
> - verified-person-bcpc for prod
we already had verified-person-bcpc-dev for dev (& localdev)
> SCJ-205: Use different BC Wallet configId for dev/test/prod

- app/Controllers/ScBookingController.cs
- app/Services/SC/ScCoreService.cs
- app/ViewModels/SC/ScCaseSearchViewModel.cs
- app/Views/ScBooking/Index.cshtml
This fixes an issue where  futureTrialHearing and fairUseSort weren't being populated after users searched for and selected a court file.
> SCJ-233: Fix for futureTrialHearing and fairUseSort not being populated

- app/ClientSrc/vue/TrialTimeSelect/FairUseBooking.vue
- app/ClientSrc/vue/TrialTimeSelect/Tabs.vue
- app/Services/SC/ScCoreService.cs
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
- database/Constants/ScGeneral.cs
- database/Constants/ScTrialDateLimits.cs
This turns the hardcoded `5` into a constant called `ScTrialDateLimits.MaxSelectionSize` that can be easily changed to affect the front and back end.
I also updated the code that sets `bookingInfo.SelectedFairUseTrialDates` to limit the list, so people can't manually inject 6 or more dates when they post the form.
Take a look and let me know if the variable/file naming is okay! I originally had it as "ScTrialDateSelection" but that's already used for other things throughout the app 😆
> SCJ-232: Refactor MaxSelectionSize into a constant

- app/Services/SC/ScCoreService.cs
- app/Services/SC/ScTrialBookingService.cs
- app/ViewModels/SC/ScAvailableTimesViewModel.cs
- app/ViewModels/SC/ScTrialEmailViewModel.cs
- app/Views/ScBooking/Emails/Email-Trial-FairUse.cshtml
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
This uses `ScPhoneNumbers.PhoneList`  to make phone numbers dynamic in the template (in one page and one email).
There's a third commit that applies auto formatting to the email template file, it shouldn't affect anything but we can drop the commit if it simplifies things.
> SCJ-237: Make scheduling phone numbers dynamic

- app/ClientSrc/vue/TrialTimeSelect/FairUseBooking.vue
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
Wording changes on the page where you pick and re-order your preferred trial dates. Another bit of content from the fair-use-booking Vue component was turned into a content slot so it can come directly from the _Trial.cshtml file.
...and now that it's a slot, I was able to remove the trial-length prop because it's no longer needed in the component.
> SCJ-238: Update date selection page template

- app/ClientSrc/vue/TrialTimeSelect/helpers.js
- app/Controllers/ApiController.cs
- app/Services/COA/CoaBookingService.cs
- app/Services/SC/ScTrialBookingService.cs
- app/Utils/ScSessionBookingInfo.cs
- app/ViewModels/SC/ScTrialEmailViewModel.cs
- app/Views/CoaBooking/CaseConfirm.cshtml
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
- app/Views/ScBooking/Partial/CaseConfirm/_FairUseBooking.cshtml
- app/Views/ScBooking/Partial/CaseConfirm/_RegularBooking.cshtml
- app/Views/ScBooking/RequestSubmitted.cshtml
- app/Views/ScBooking/TrialBooked.cshtml
- taskrunner/Utils/LotteryEmailViewModel.cs
The wireframes specify a datestamp format with no comma to separate the weekday name, and no zero padding for the day of the month. I've updated the timestamps app-wide, including one in the COA section. I'll make a note in the ticket for QA to check all parts of the app.
```md
was:
Tuesday, July 09, 2024
now:
Tuesday July 9, 2024
```
Most of the dates and times in the wireframes don't specify a format ("[date]") but QA suggested we make them all consistent.
> SCJ-245: Update date formats

- app/ClientSrc/vue/HearingTimeSelect/HearingTimeSelect.vue
A "Z" was being appended to a timestamp back when we were using UTC time. Now that the server has the pacific timezone configured, the "Z" was messing up the real time zone and making the dates invalid on non-trial SC bookings.
This fixes it so the dates will be valid again in non-trial bookings such as JCC
> SCJ-249: Remove hardcoded timestamp "Z"

- app/ClientSrc/vue/TrialTimeSelect/FairUseBooking.vue
I originally misinterpreted the requirements in the wireframes. This change will hide the notice that says "Remove a chosen date before adding another." until you try to select a 6th item. Previously, it would just show as soon as you selected your 5th item.
I also flipped it from being a "hide" to a "show" variable because it makes more sense in this new context.
> SCJ-243: Hide "selection full" alert until a 6th item is clicked

- app/ClientSrc/vue/TrialTimeSelect/FairUseBooking.vue
The wireframes specify that the "3/5 selected" counter text should be hidden if there are fewer than 5 options available.
(5, or the `maxSelectionSize`)
I missed a lot of stuff in the wireframes... should have had my screen maximized 🙈
> SCJ-242: Hide limit counters if too few dates are available

- app/Controllers/ScBookingController.cs
- app/Services/DataWriterService.cs
- app/Views/ScBooking/BookingType.cshtml
QA reported some problems when you put in a huge number like 999999 for the trial length. 
After some discussion we decided to just limit it to a realistic number. I see there's already validation code in the data writer service:
```csharp
if (
!bookingInfo.EstimatedTrialLength.HasValue
|| bookingInfo.EstimatedTrialLength.Value < 1
|| bookingInfo.EstimatedTrialLength.Value > 99
)
{
throw new InvalidOperationException(
"HearingLength must be greater than zero and less than 100"
);
}
```
So I've limited the input to a maximum value of 99 to match that.
> SCJ-244: Limit trial length to 40 days

- app/ClientSrc/vue/HearingTimeSelect/HearingTimeSelect.vue
- app/Services/SC/ScCoreService.cs
- app/Utils/ScSessionBookingInfo.cs
- app/ViewModels/SC/ScAvailableTimesViewModel.cs
Removed the "js ticks" logic when converting selected dates for non-trial conference bookings. `SelectedConferenceDate` was already stored as a string, so I just replaced it with an ISO date string and parsed that instead.
This fixes `SelectedConferenceDate` being off by 7 hours as it was still being treated as UTC in the ticks conversion.
I don't know what the "containerId" stuff is doing - maybe we can remove that some day too?
> SCJ-249: Fix bookingTime string, remove ticks variables

- app/ClientSrc/vue/TrialTimeSelect/RegularBooking.vue
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
Updated the copy on step 3 to say "day/days" correctly if the trial length is 1 or more. This is consistent with the rest of the app now.
I also added a ":" to the trial length string in 2 places:
> Trial length 4 days
> Trial length: 4 days
This is also for consistency with how it's shown in the rest of the app. Winnie said she'll confirm later this week but I'm guessing this is what we'll decide to do. Easy to undo, if not.
> SCJ-251: Update trial length copy

- app/Views/CoaBooking/CaseSearch.cshtml
- app/Views/Home/Sso.cshtml
- app/Views/ScBooking/Index.cshtml
- app/Views/ScBooking/Partial/AvailableTimes/_Trial.cshtml
Added the "external link" icon on the links that point to the scheduling pages, as well as the "register for a bceid / bc wallet" links
Some whitespace changed from the editor auto-formatting. I guess if you're not using VS Code to edit these files, the auto-formatting settings in .vscode/ would do nothing! I didn't consider that when I set it up 😅
> SCJ-241: Add "external link" icons

- openshift/helm/scjob/values-prod.yaml
- openshift/helm/scjob/values.yaml
Added resource limits to helm charts
These are being included in the app and taskrunner deployments where you see a line like this...
```
resources:
{{ toYaml .Values.taskrunner.resources | indent 12 }}
```
> SCJ-253: Add resource limits to helm charts

- app/ClientSrc/sass/global.scss
- app/Views/ScBooking/_Layout.cshtml
This adds some spacing, and a horizontal line between the title and the mobile menu.
These changes don't apply to larger screens because the "LOG OUT" link is positioned horizontally.
> SCJ-255: Add separator to mobile menu

- app/Controllers/ScBookingController.cs
- app/Services/SC/ScCoreService.cs
- app/Utils/ScSessionBookingInfo.cs
- app/ViewModels/SC/ScAvailableTimesViewModel.cs
- app/ViewModels/SC/ScCaseSearchViewModel.cs
- database/Migrations/20240820223702_CaseNumberString.Designer.cs
- database/Migrations/20240820223702_CaseNumberString.cs
- database/Models/ScTrialBookingRequest.cs
- tests/Helpers/CsvMapping.cs
- tests/LotteryServiceTests.cs
Changed `CaseNumber` from an integer to a string so it would keep leading zeros
Added additional validation to block strings containing non-digits.
> SCJ-250: Allow leading zeros on case numbers

- SCJ.Booking.sln
- app/Services/SC/ScCacheService.cs
Virtoria won't be using the lottery system for family cases, but they will be using the lottery system for everything else.  
This change allows the fair use tab to be hidden when a user is booking a trial for a family case in Victoria.
> SCJ-270: Special treatment for family court class (E)

- taskrunner/Program.cs
- taskrunner/servicesettings.json
This setting will allow us to slow down the taskrunner if we are debugging issues with the API. 
Add an environment variable to the TaskRunner deployment on Openshift
e.g.
AppSettings__PollingFrequencySeconds=30
The default is 5 seconds.  When the taskrunner first starts the polling frequency is printed to the logs
> SCJ-269: Make the taskrunner polling interval configurable

- taskrunner/Services/LotteryService.cs
This is the same as #233 except it exits with error code 1 instead of re-throwing the exception. (a48b20f)
It still has the test line that will always throw an exception, so we can test what actually happens in Openshift. I'm not 100% sure this won't kill the pod as well but it _should_ just gracefully exit the script.
> SCJ-271: Add fatal error condition for lottery service
